sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-148.pdf --upload --lsstdoc LDM-148.tex --env=travis --ltd-product $PRODUCT --docushare-url https://ls.st/ldm-148*"
env:
  global:
    - PRODUCT="ldm-148"
    # Add LSST the Docs credentials
    - secure: "YPq8wqTffziwT/3Tk5mBFOColcjmhwOxnfcdBqF2ECPInbPJVgVHSea6MA1cXbd97vRWuL18LQSGKH1De0FAJ220Fqcjt0OdF6BbWqOopDN5JBmSxBY8+t15YwyJjKSPd1uoRMuLq+DdhYBZgbVJYk63xwM+Z5wemY58uzSxqFsrd4HIQmtnmZsrSMj2Ktn/jW3WOjziGjhAEy3vKRnPFcNQRtTwS5mbs//LK9h0JO/0wuHHscBjIBq0sDLQXjKKdOHqTZwA+vO1enyc64lkyBahdcFPc/eXovISMRmaWimIXC+lGNQ6rR7f0lo1OxTgbiwKBKWojKztKRHvsdJSc++nl8R0ZhvJDzsr4Yz+Psg4PDCDxUEhiwptGTqlvHLk2rtGgCo74PDBWHDgC6zsJrx9zAcGYPk1ab4+uAoujc97/zbT+gBBFgV0n5PddDDNsHhl58gmb6D/p4XQuLvscIrVxSINfGHDD/gNIhZ50uiFm6qTs9hFz6mKIDjdVBdCnZImMivWBikS/aCpUr4DibzsXkAOsuZc/cuJ2j0Ue8OxIHaMOoRODoT0OfV1JCftgL9u8DO/hh3XkoR4KgIwR81MV7vsYKF4afV/Qn0pwPU05xisfMEI1z/VA4BlfzKHrH/nAIcAHV2iLz2GSzd83ugOiJv83M++1BGhSG5Fzgs="
    - secure: "EaRUl/cSAL1H+XZXY9U9l3DRiO+f0OzJeUOUaq0oNL8gvquFoUlrJUXuSWeP6CSeRz/RqPg7I/tyoDjes65P9ju+5thKdXHZIG1w6jQoB64Qv81Vt73Wla1VcrxrDmHoeT5u4BnspuSowR1kBtNaodK8YYfiOfUObPQQPnJpkn/nLA0tOfcRQc3du3pKCkAWkBJXAEQSuaJYfy7HIEFRg1pNabZfb0KjXWMtBRUjfTyhMLYYReoVscz6cRae2BGi0dC2eMJG88NGo00jsJ5aqVkezHflrhizGI/0Zp706oSOdGAoSIRxmdccsngi/MdPPeTwK9NgasQikIpBNkc+Z5cUFQufHqHkx8iDb3QQIIFnS0yGs4eOT6YOBKYSc8c+vBGGDv7hQxF38+mIjUTuDZt59/dntGhaBqmlY4SH7LqXdQrTUL+pr7PNQFVxI1kTHmaHa4vvqIYy9BK2Ua2bk4ltAaDqT7YRo4+HQwFr4jrRw7I4tKU7NlTYBczM0SAHf7O8XdPFcOtZ3fipK/RSb1H4Jn2VgmDMpYpj9XkM66FGFN/zUfXt6WdTJLTv+HprBwIYBaJhlF24ENa1U803mF20MGX7Xv9cja1ZOWEcqfHFS82GvNBUN+mn6HGy/v35eK4NVY8HJHZUSUPrF3LlayzZw100WexnHPsHlURPtwc="
